### ISSUE TITLE
d0rker stops working at around 2-3K URLs

### ISSUE THREAD

**Issue by r1Ns3** [v3n0m-Scanner/V3n0M-Scanner#103]
It just hangs there, not sure where to go from here.

I have tried running a vpn, then when limited changing the ip by connecting to another server. This does not work.

**Comment by NovaCygni** [comment]
Point 1) D0rker doesnt "Hang" unless theres a good reason... clue wouldve been in the output displayed when it hang, this output is normally very descriptive and logic would indicate maybe you shouldve posted the output.
Point 2) "Hanging" is normally the result of someone trying to tamper with V3n0Ms files to try making V3n0M into a creditcard stealing tool, laughably this is very common and the people who try it, wont get very far as V3n0M has protections within it to stop specific tampering.
Point 3) "Bug Reports" which have zero information of value and simply have "It r not work" without any feedback or even the output in the program when it "Hang" have always been and will always be paid little to no attention...


Please post the actual output from the V3n0M scan when its stopped/Frozen, VPNs/Proxies dont affect the scanners abilities and the "d0rk scanner" is a unblocking scanner, thus, doesnt get scans blocked due to IP address in use.

**Comment by r1Ns3** [comment]
I recently found out that after a few thousand searches, google IP bans for a few minutes, the issue is solved and turns out was not a hang just a mistake on my part, however the tool is running considerably slow. A suggestion might be if you had the time to incorporate multiple proxy support for big searches?

Thanks for the help anyway.

**Comment by NovaCygni** [comment]
V3n0M doesnt use anything to do with google, google IP bans are well known, and even though they can be avoided they are not worth the time to do ass even once Captchas are bypassed, the results come back slower than bing or yahoo.
I would advise looking into your IP itself as it sounds like you could be using a throttled connection, "Time x D0rk searches == Results" is still a higher ratio than any other d0rker, the "Full scan" ie all d0rks would take a very very long time but its up to the user how many d0rks at once they wish to search. 

Also,. Misc Options (* Num 7 on main menu *) already has full Tor/Proxy support....
