### ISSUE TITLE
[Enhancement] Increase max threads

### ISSUE THREAD

**Issue by AdaptCharm** [v3n0m-Scanner/V3n0M-Scanner#127]
Please increase the max threads from 500 to 1000. Optionally, add a --threads parameter which accepts any input number.

There are actually some people who got massive CPU cores, like me.

**Comment by d4op** [comment]
Do it yourself and Commit bro

Von meinem iPad gesendet

Am 26.12.2017 um 11:47 schrieb Jamie Isaksen <notifications@github.com<mailto:notifications@github.com>>:


Please increase the max threads from 500 to 1000. Optionally, add a --threads parameter which accepts any input number.

There are actually some people who got massive CPU cores, like me.

**Comment by NovaCygni** [comment]
My Laptop has become a paperweight due to a microfracture on the GPU, as ive extensive legal costs atm replacing it is sadly not a priority and could be a matter of months till its replaced, best case scenerio... look through the code for the threads and just edit it yourself for the meanwhile. By all means im happy to accept donations towards a replacement laptop but i doubt itll ever happen :/

**Comment by NovaCygni** [comment]
DnS module is the only one that has a threads limiting to 500 (mustve been overlooked) you can change it to whatever you want it shouldve actually been asking for a value anyway, but again, im down to a mobile phone until I can replace my laptop so unless someone else sumbits code changes that im happy to merge and commit itll be a few months till I can do any of the planned updates v3n0m requires.

**Comment by NovaCygni** [comment]
Ohhh and if ur referring to the message thrown by this line 'numthreads = input('\nEnter no. of threads, Between 50 and 500: ')' The faults mine, the upper limit has been removed for years itd actually accept any value under 10.000 threads.
