### ISSUE TITLE
Confirmed: [Bug] UnicodeEncodeError - Undefined Unicode not handled.

### ISSUE THREAD

**Issue by AdaptCharm** [v3n0m-Scanner/V3n0M-Scanner#128]
> _"Anything that can go wrong will go wrong"_ - Murphy's law

I'll try to make this as brief as possible; started a massive scan, **1.3m** urls collected in total within **5.47** hours, upon saving the valid urls (**21.7k**) I received this error:

https://i.gyazo.com/a6646e5f6508cf0fc19cba9710b5618a.png

**My VPS specs:**
Processor: 8 CPU Cores, Intel(R) Xeon(R) @ 2.30GHz 
Installed memory (RAM): 52 GB
OS: Windows Server 2016 Datacenter 64bit
https://i.gyazo.com/ebfe27d3ff452e4665327aa5026d839a.png
https://i.gyazo.com/00578d9c5c66e9e5733d37055df5bbfd.png

**Comment by NovaCygni** [comment]
./facepalm Ok I gotta hands up again and admit, I knew this was potentially a problem, knew I shouldve had parsing for different Unicode versions, I kept putting it of for that long I totally forgot to even fix it... Sorry :/ Thanks for reminding me though and it WILL be fixed in the next update, though sadly thats not any time soon due to CAFEDEAD ring0 fail on my Gpu making my laptop a paperweight.

**Comment by NovaCygni** [comment]
Should be fixed as of Version 425. Thanks for you patience.
