### ISSUE TITLE
Dorking

### ISSUE THREAD

**Issue by eperkso0** [v3n0m-Scanner/V3n0M-Scanner#159]
Am I able to change the dorks list? Because I have dork for geo targeted site. 

ex:
webshop.php?cust= site:de

or just keep the normal dork without site:de?

What if im targeting any domain, dont fill the geo filter? Just enter on it?

**Comment by d4op** [comment]
Read the code. Its simpel.

Am 20.03.2019 um 02:31 schrieb eperkso0 <notifications@github.com<mailto:notifications@github.com>>:


Am I able to change the dorks list? Because I have dork for geo targeted site.

ex:
webshop.php?cust= site:de

or just keep the normal dork without site:de?

What if im targeting any domain, dont fill the geo filter? Just enter on it?

**Comment by NovaCygni** [comment]
Isnt required if you used the program properly you would know to do a geo targeted site you can use the first option, namely, domain... which does exactly what you were asking about by requesting the dork+domain requested.
