### ISSUE TITLE
Docket scan error

### ISSUE THREAD

**Issue by Chomikmarkus** [v3n0m-Scanner/V3n0M-Scanner#226]
After running scan in docker i get this error with permission
Traceback (most recent call last):
  File "/opt/scan/src/v3n0m.py", line 1667, in <module>
    f_menu()
  File "/opt/scan/src/v3n0m.py", line 1296, in f_menu
    f_scan()                                                                                File "/opt/scan/src/v3n0m.py", line 876, in f_scan
    scan_option()
  File "/opt/scan/src/v3n0m.py", line 915, in scan_option
    cctv_log_file = open("v3n0m-cctv.txt", "a", encoding="utf-8")
PermissionError: [Errno 13] Permission denied: 'v3n0m-cctv.txt'

**Comment by vittring** [comment]
CCTV is a work in progress module.

Were you trying to execute that option?

**Comment by Chomikmarkus** [comment]
No was executing v3n0m.py

**Comment by vittring** [comment]
That doesn't answer my question in the slightest. Please be more descriptive.

**Comment by vittring** [comment]
4 hours later, and no further information. Simply put, when reporting Issues, please refer to the [Bug Fixes](https://github.com/v3n0m-Scanner/V3n0M-Scanner/blob/master/CONTRIBUTING.md#bug-fixes). Provide meaningful details on the issue and be prepared to answer follow-up questions about logs (Python, Poetry, syslogs).

**Comment by kattstof** [comment]
i get the same error with docker aswell on windblows (just tested) 
i'm assuming its a problem with how docker is setting up the file permissions.(ex. owner of the file is admin but user isnt admin) i don't really use docker so i couldn't really troubleshoot that part.
the problem at hand is , when running a dork scan when it finishes scan options is called, when scan options is  called the cctv , dork , etc list variables are defined globally but the cctv list file cant be opened because no "permission"
since cctv is still unfinished i'm going to go ahead and switch the uniformity and only open the cctv list if the user presses that option.

**Comment by vittring** [comment]
Docker by default runs as a privileged user but I added a jail shell and non-root user to prevent someone exploiting the session and gaining a foothold on the host. I may have added in the CCTV files with different permissions at some point. I'm troubleshooting now.

**Comment by vittring** [comment]
Fixed. Sorry took so long lol.

**Comment by kattstof** [comment]
what ended up being the cause if you don't mind me asking?

**Comment by vittring** [comment]
The changes you made fixed the issue in the source but the Dockerfile was still set to draw the source from my repo. So I pulled your changes to fix it on my end. Then I set the Dockerfile to also clone the main repo.
