### ISSUE TITLE
adminfinder.py

### ISSUE THREAD

**Issue by tty666** [v3n0m-Scanner/V3n0M-Scanner#38]
I will have to look and fix this one also.
I started yesterday but it's still unstable ...
I have to leave now so will work on it when I am back

**Comment by NovaCygni** [comment]
there was another version of it floating about using Asyncio method but alas it was deleted during a emergency by accident... shouldnt be much of a change compared to this version, think aside from the Asynio aspect itd just added a port-checker to it aswell as I realised alot of Admin pages not only use ie: panel.html but can also be accessed via the ports number, ie example:17821.
Sadly ive very little free time this month due to family obligations but Ive every intention of getting back to it when I have a chance :) after all gotta add in the Cloudflare IP resolver still and the Honeypot remote fingerprinting/detecting scripts (* requiring me to finish the Asyncio TCP scanner *)
