### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by HBlackOne** [v3n0m-Scanner/V3n0M-Scanner#80]
Traceback (most recent call last):
File "setup.py", line 3, in
import setuptools
ImportError: No module named 'setuptools'

**Comment by NovaCygni** [comment]
`sudo pip3 install setuptools`
Then id suggest
`sudo pip3 freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 sudo pip3 install -U`
Just to make sure your Pythons up to date as frankly, you should already have setuptools ;)

**Comment by HBlackOne** [comment]
sudo: pip3: command not found
 ?????

2017-02-19 18:41 GMT-05:00 NovaCygni <notifications@github.com>:

**Comment by NovaCygni** [comment]
```
sudo apt-get remove python3-pip
sudo apt-get install python3-pip
```
You  couldve also tried ```sudo python3 pip -m install setuptools``` depending which OS your on, this is though, not a issue with V3n0M and shows a underlying issue with you havnt got Python installed correctly.

**Comment by HBlackOne** [comment]
when i start my kali linux i have some problems messgaes like that one :
firmeware failed to load iwlwifi ...
check systemctl status networking.service
tahts what happen when i check the command :
Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor
preset: enabled)
   Active: failed (Result: exit-code) since Thu 2017-02-23 22:16:46 EST;
2min 3s ago
     Docs: man:interfaces(5)
 Main PID: 272 (code=exited, status=1/FAILURE)

Feb 23 22:16:35 hblack systemd[1]: Starting Raise network interfaces...
Feb 23 22:16:36 hblack sh[262]: ifquery: unknown interface eth0
Feb 23 22:16:40 hblack ifup[272]: ifup: unknown interface eth0
Feb 23 22:16:46 hblack systemd[1]: networking.service: Main process exited,
code=exited, status=1/FAILURE
Feb 23 22:16:46 hblack systemd[1]: Failed to start Raise network interfaces.
Feb 23 22:16:46 hblack systemd[1]: networking.service: Unit entered failed
state.
Feb 23 22:16:46 hblack systemd[1]: networking.service: Failed with result
'exit-code'.
~
~
~
~
so please can u help me with that ??


2017-02-22 12:26 GMT-05:00 NovaCygni <notifications@github.com>:

**Comment by kattstof** [comment]
Kali is known to be an issue with v3n0m best thing to do is update v3n0m and python3 then use option 2 in the recovery menu if all else fails use arch Linux it works flawlessly

**Comment by NovaCygni** [comment]
His issue isnt anything to do with V3n0m, hes whining about his Kali Linux giving output when it boots up, which means he cant even use a spoon-feeding hacker OS, thus Archlinux is of no help to him.

His output btw is very self explanatory, he doesnt have a eth0 port to use yet has clearly copied the "if_up/down" script from somewhere and has failed to install even that correctly, nothings failing system wide either its just letting him know his "Cheat" to enable monitor mode on wireless, isnt working, which if he also cant work out how to manually up/down a device let alone what the name of the device is, he shouldnt be encouraged to even attempt it yet.
The issue remained closed because his 'issue' is wildly offtopic from v3n0m, and is nothing to do with it.

PS> All the Kali 'Issues' got resolved before xmas ;o

**Comment by kattstof** [comment]
I was trying to spoonfeed him how to solve the setuptools error as dumbed down as I could. Being as he wasn't bright enough to copy pasta the commads. The error log wasn't what i was answering. xD oi, the kali issues is good to hear i ghosted for abit so i was afk during that time.

**Comment by NovaCygni** [comment]
Yeh atm the only issue is updates now, oh and to refinish the new LFI - RCE method, Finish the Py3 Wifite module so it all works and add the Netgear remote router reset exploit to it.... oh and Expand the cloudflare resolver to also resolve the real IP for blazingfast.io addresses aswell.
