### ISSUE TITLE
Custom sqli list checking bug

### ISSUE THREAD

**Issue by kattstof** [v3n0m-Scanner/V3n0M-Scanner#87]
can only concatenate list not str

**Comment by NovaCygni** [comment]
Ill push the hotpatch later its like a 2 minute fix.

**Comment by NovaCygni** [comment]
Sorry mate completely forgot, will do after this coffee and will Push (* only just woke up, ironically, was my first though :/ *)

**Comment by NovaCygni** [comment]
Ok ive got a better way to fix this and add some more "Handling" for the compiled lists, atm im not really happy with the way its just dumping the txt files in v3n0ms own location, bear with me ill push a update next couple days max, I should have this LFI -> RCE issue sussed aswell so thatll be 2 birds done.

**Comment by kattstof** [comment]
yeh i wouldve hotpatched myself but im only on mobile for the next few weeks due to family issues .  Also, scans always produced some junk urls in the newer versions . but.i.assume that and.issue on bings end. Ah how i miss being.able to multiscan google without captcha worries

**Comment by NovaCygni** [comment]
Sadly with the new Captcha system theres just so long a wait between the loading of new captchas and even then only a 33% hit rate of success otherwise more waiting, thus, it becomes unfeasible atm :( but I think some of the junk is likely filterable out if you spot any good example easy to reproduce lemme know ill add a filter to the search requests to not display x results, same as is done with some of the filtering already.

**Comment by kattstof** [comment]
Will do Mate cheers!

**Comment by NovaCygni** [comment]
Pushed:Fixed:Resolved @kattstof 
Any tips/suggestions or new bugs lemme know mate :+1:

**Comment by kattstof** [comment]
skip to sqli still not patched :# 
 File "v3n0m.py", line 1271, in <module>
    fmenu()
  File "v3n0m.py", line 1129, in fmenu
    injtest()
  File "v3n0m.py", line 520, in injtest
    hits = str(resp.read())
AttributeError: 'str' object has no attribute 'read'

**Comment by NovaCygni** [comment]
:/ Tested multiple lists now, the only time I can produce this error message is with a empty list (* I should probably throw a exception for that, tbh *) :+1: 

You tested it with a empty file? Not sure why yourd be getting this, the custom checking is done entirely differently now :/ 
Heres what I get from a test list.
`Enter file name and location: /home/novacygni/Desktop/listed.txt

http://shop.afvmodeller.com/customer/product.php?productid=18183&amp;cat=&amp;page= is vulnerable --> MySQL Classic
http://www.tbnnetworks.com/church/net_pressarticle.php?ID=72 is vulnerable --> MySQL Classic
https://www.westonsigns.com/product.php?productid=1895 is vulnerable --> MySQL Classic
http://www.qh-today.com/index.php?Seite=hengstansicht&amp;Hengst=152 is Vulnerable --> MiscError
https://www.nshcoa.com/index.php?p=site is vulnerable --> MySQL Classic
http://www.kdep.gr/index.php?lang=gr is vulnerable --> MySQL Classic
http://www.grillpro.com/accessories.php?type=6 is vulnerable --> MySQL Classic
http://www.elleraconte.com/print.php?numero=11428 is Vulnerable --> MiscError
http://www.gatwickkoi.com/details.php?id=473 is vulnerable --> MySQL Classic
http://www.expertins.com/insurance.php?id=1 is vulnerable --> MySQL Classic
http://www.music-scores.com/midi.php?sheetmusic=Christopherson_Beach_Path_Bike_pno is vulnerable --> MySQL Classic
http://kevesgloballeasing.com/policy.php?id=3 is vulnerable --> MySQL Classic
http://www.thornbridgebrewery.com/shop.php?catid=2 is vulnerable --> MySQL Classic
http://www.torqwrench.com/tools/genPage.php?type=C&amp;drive=3 is vulnerable --> MySQL Classic
http://www.godslearningchannel.com/site/watch.php?program=24 is vulnerable --> MySQL Classic
http://bellasamui.com/koh-samui-shopping.php?id=8 is vulnerable --> MySQL Classic
http://www.islamic-invitation.com/TVs.php?my_TVs=1 is Vulnerable --> MiscError
http://www.jockstrapcentral.com/productdisplay.php?product=36005 is vulnerable --> MySQL Classic
http://www.augustea.com/policy.php?id_policy=1 is Vulnerable --> MiscError
http://www.deccanherald.com/pages.php?id=600027 is Vulnerable --> Syntax error
`

**Comment by NovaCygni** [comment]
Oh as for: "sqli/xss/lfie-rce testing Add shellfinder + Bringback cctv scanning (Seperate from sqli testing opt)"
The Full Sqli/xss/lfi-rce multiple option will be thrown back in likely sooner than later as im starting to pull features together for chaining attacks (* at least in my private version atm anyway *)
Shellfinder is a trivial and easily added thing, that was only not included due to the large amount of "Honeypot-Shells" lurking around, technically it would "Trigger" every honeypot it probed and if a noob user had no VPN/Protection, well.,, wouldnt be good for the nublet (* I could probably do a couple "Are you sure yourve got a VPN or Proxy running" checks tbh, so I may actually reconsider adding that *)

The CCTV is again, trivial to re-add but sadly it will be time consuming as ill need to verify and remove CCTV d0rks from the main d0rks list, aswell as adding the new CCTV models since 2014 when the list was compiled...

**Comment by kattstof** [comment]
I honestly can't figure it out ,ive tested a few lists and getting the error. My buddy tried on his box and isnt. Currently setting up a VM to see if it has to do with my enviroment

**Comment by NovaCygni** [comment]
Ive re-opened the issue incase theres something thats a underlying larger problem, As it stands I can only reproduce with the empty list, you could try removing v3n0m outright and uninstalling it, and then reinstalling from scratch.

**Comment by kattstof** [comment]
I've tried from a fresh vm and still seem to be getting the error . Cant quit figure it out sadly.

**Comment by kattstof** [comment]
patched and commited cheers
