### ISSUE TITLE
Problem with setup.py

### ISSUE THREAD

**Issue by vadimk2016** [v3n0m-Scanner/V3n0M-Scanner#99]
When I try to install with using 
`python3.6 setup.py install --user`
I get an error:
`/usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'`
This happend in my docker container from kalilinux/kali-linux-docker and Windows.

**Comment by NovaCygni** [comment]
`Note for Kali users: Please make sure you have installed --> apt-get install python3-dev apt-get install python-dev`
did you miss that on main page?

**Comment by vadimk2016** [comment]
Thanks, you too.
I tried this but the error remained, also I tested:
OS: Kali, Windows
Docker: Kali, Debian
Same error `/usr/local/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'`

**Comment by NovaCygni** [comment]
Ah this would probably be related to https://github.com/v3n0m-Scanner/V3n0M-Scanner/issues/95 
As I dont use Kali, have no use nor knowledge of Dockers apart from "They exist", its unlikely ill be making a docker image myself. If someone wishes to adopt the Docker project themselves and push the code source Im happy to include it, but, im not going to be doing it myself due to other priorities.

I am curious though as to why your running a Docker at all, surely abandoning winblows to its own partition merely for gaming, and using a REAL Linux install would be far better of, you could even ditch that nasty Kali and install something abit more savage like Blackarch Linux ;)

**Comment by vadimk2016** [comment]
It seems that I did not write clearly. Docker containers can be built on certain operating systems like Kali or Debian, and under OS I meant full-fledged OS and not only Docker containers.

**Comment by NovaCygni** [comment]
installed and ran fine on the Kali VM i just tried :/ So im not really sure... well anyways ill be replacing the setup.py file soon anyway with one with "Try/Excepts" in it so when one install method fails itll move onto a different method, hopefully that will resolve it, but if you can get anymore feedback or information on your setup it may help... I know theres alot of Kali users hopefully one of them knows whats wrong.

**Comment by vadimk2016** [comment]
Here is script that I use to install on my Kali VM:
```bash
apt-get install -y build-essential checkinstall libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev python-setuptools python3-dev python-dev
wget https://www.python.org/ftp/python/3.6.0/Python-3.6.0.tgz -P /tmp/python36-dist
tar xzf /tmp/python36-dist/Python-3.6.0.tgz -C /usr/src
cd /usr/src/Python-3.6.0 && ./configure && make altinstall
wget https://github.com/v3n0m-Scanner/V3n0M-Scanner/archive/master.zip -P /tmp/venom-dist
cd /tmp/venom-dist && unzip master.zip && mv V3n0M-Scanner-master /opt/venom
cd /opt/venom && python3.6 setup.py install --user
